// <auto-generated />
using System;
using CrudEmissoras.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CrudEmissoras.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20210512225223_CriacaoBD")]
    partial class CriacaoBD
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CrudEmissoras.Models.Audiencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Data_hora_audiencia");

                    b.Property<int>("Emissora_audienciaId");

                    b.Property<int>("Pontos_audiencia");

                    b.HasKey("Id");

                    b.HasIndex("Emissora_audienciaId");

                    b.ToTable("Audiencias");
                });

            modelBuilder.Entity("CrudEmissoras.Models.Emissora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Emissoras");
                });

            modelBuilder.Entity("CrudEmissoras.Models.Audiencia", b =>
                {
                    b.HasOne("CrudEmissoras.Models.Emissora", "Emissora_audiencia")
                        .WithMany()
                        .HasForeignKey("Emissora_audienciaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
